version: '3.8'

services:
  web-server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MAIN_DB_HOST=${MAIN_DB_HOST}
      - MAIN_DB_PORT=${MAIN_DB_PORT}
      - MAIN_DB_NAME=${MAIN_DB_NAME}
      - MAIN_DB_USER=${MAIN_DB_USER}
      - MAIN_DB_PASSWORD=${MAIN_DB_PASSWORD}
      - MAIN_DB_SCHEMA=${MAIN_DB_SCHEMA}
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${MAIN_DB_USER}
      - POSTGRES_PASSWORD=${MAIN_DB_PASSWORD}
      - POSTGRES_DB=${MAIN_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 